In [6]:
import numpy as np
arreglo = np.zeros((2,3))
arreglo

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [14]:
arreglo[:] = 58
arreglo

array([[58., 58., 58.],
       [58., 58., 58.]])